# Generated by Django 3.0.5 on 2020-06-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Displayer', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloudImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud', to='Displayer.NspProduct')),
            ],
        ),
    ]
